api/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('physio/get/', api_get_physio.as_view()),
    path('nurse/get/', api_get_nurse.as_view()),
    path('patient/get/', api_get_patient.as_view()),
    path('report/get/', api_get_report.as_view()),
    path('test/get/', api_get_test.as_view()),
    path('test/get/<int:id>', api_get_test_one.as_view()),
    path('test/create', api_create_test.as_view()),
    ]

heal/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from accounts.views import index
from .views import home_page
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    path('nurse/', include('nurse.urls')),
    path('patient/', include('patient.urls')),
    path('report/', include('report.urls')),
    url('',include('adminpage.urls')),
    path('', home_page),
    path('physiotherapist/',include('physiotherapist.urls')),
    path('lab1/',include('lab1.urls')),
    path('samplecollector/',include('samplecollector.urls')),
    path('blog/', include('blog.urls')),
    path('api/', include('api.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

lab1/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from .views import *



app_name='lab1'

urlpatterns = [
    path('',views.index,name='index'),
    path('make_profile/',views.make_profile,name='lab_make_profile'),
    path('add_test/',views.add_test,name='add_test'),
    path('modify_profile/',views.modify_profile,name='lab_modify_profile'),
    path('show_profile/',views.Show_Profile,name='lab_show_profile'),
    path('show_tests/',views.tests, name='lab_show_tests'),
    path('lab_bookings/',views.show_bookings, name='lab_show_bookings'),
    path('assign_collector/',views.assign_collector, name='lab_assign_collector'),
    path('collected_samples/',views.collected_samples, name='lab_collected_samples'),
    path('reports/',views.reports, name='lab_reports'),
    path('home/', lab_home, name='lab_home'),
    path('date_add/',views.DateCreate.as_view(),name='lab_date_create'),
    url(r'^date_add/(?P<pk>[0-9]+)/slot/$', views.create_slot, name='lab_create_slot'),
    path('slots/',views.show_slots,name='show_slots'),
    path('complaint_feedback/', views.ComplaintFeedbackCreate.as_view(template_name="lab1/new_file.html"), name='lab_complaint_feedback'),
    path('show_complaint_feedback/', views.show_complaint_feedback, name='lab_show_complaint_feedback'),
    url(r'^delete_slot/(?P<slot_id>[0-9]+)$',views.delete_slot,name='lab_delete_slot'),
    url(r'^select_collector/(?P<pk>[0-9]+)$',views.select_collector,name='select_collector'),
    url(r'^assign_collector_to_test/(?P<collector_id>\w+)/(?P<booking_id>\w+)/$',views.assign_collector_to_test,name='assign_collector_to_test'),
    ]

physiotherapist/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from .views import *



app_name='physiotherapist'

urlpatterns = [
    path('',views.index,name='index'),
    # path('slot/', views.home),
    path('make_profile/',views.make_profile,name='make_profile'),
    path('modify_profile/',views.modify_profile,name='modify_profile'),
    path('show_profile/',views.Show_Profile,name='show_profile'),
    path('home/', physio_home, name='home'),
    path('date_add/',views.DateCreate.as_view(),name='Date_Create'),
    url(r'^date_add/(?P<pk>[0-9]+)/slot/$', views.create_slot, name='create_slot'),
    path('slots/',views.show_slots,name='show_slots'),
    path('complaint_feedback/', views.ComplaintFeedbackCreate.as_view(), name='complaint_feedback'),
    path('show_complaint_feedback/', views.show_complaint_feedback, name='show_complaint_feedback'),
    url(r'^delete_slot/(?P<slot_id>[0-9]+)$',views.delete_slot,name='delete_slot'),
    path('appointments/',views.show_appointments,name='show_appointments'),
    path('work_history/',views.work_history,name='work_history'),
    # path('attend_appointment',views.show_slots,name='show_slots'),
    url(r'^attend_appointment/(?P<appointment_id>[0-9]+)$',views.attend_appointment,name='attend_appointment'),
    ]

report/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name='report'

urlpatterns=[
    path('',views.index,name='index'),
    # url(r'^prescription_add/(?P<appointment_id>[0-9]+)$',views.PrescriptionCreate.as_view(),name='Prescription_Add1'),
    url(r'^report_add/(?P<booking_id>[0-9]+)$',views.ReportCreate.as_view(),name='Report_Add1'),
    # path('prescription_add/',views.make_prescription,name='Prescription_Add'),
    url(r'^(?P<pk>[0-9]+)/$',views.DetailView.as_view(),name='detail'),
    url(r'^(?P<report_id>[0-9]+)/create_item/$', views.create_item, name='create_item'),
    path('name-autocomplete/',views.LabTestAutocomplete.as_view(),name='name-autocomplete'),
    url(r'^(?P<report_id>[0-9]+)/print/$', views.print, name='print'),

]

lab1/forms.py
from django.forms import ModelForm
from django import forms
from .models import LabSlot1, Lab1, Test1

# class SlotForm(ModelForm):
#     class Meta:
#         model = Slot
#         fields = ['time_start', 'time_end']
        # widgets = {
        #      'time_start': DatePickerInput(), # default date-format %m/%d/%Y will be used
        #      'time_end': DatePickerInput(format='%Y-%m-%d'), # specify date-frmat
        #  }

# from pyuploadcare.dj.models import ImageField
class Add_Profile(forms.ModelForm):

    # email_id=forms.CharField(widget=forms.EmailInput)
    dob=forms.DateField(
        widget=forms.DateInput(
        attrs={
        'type':'date',
        }
        )
    )
#     user = forms.CharField(
#     widget=forms.TextInput(attrs={'readonly':'readonly'})
# )
    class Meta:
        model=Lab1
        exclude = ('user','verified','email_id',)

    def clean_mobile_no(self):
        mobile_no = self.cleaned_data['mobile_no']
        if len(str(mobile_no)) != 10:
            raise forms.ValidationError('enter  a 10 digit number')
        return self.cleaned_data['mobile_no']

class Modify_Profile(forms.ModelForm):
    # email_id=forms.CharField(widget=forms.EmailInput)
    # profile_photo= ImageField(blank=True, manual_crop="")
    class Meta:
        model=Lab1
        exclude=('user','gender','verified','rating')


    def clean_mobile_no(self):
        mobile_no = self.cleaned_data['mobile_no']
        if len(str(mobile_no)) != 10:
            raise forms.ValidationError('enter  a 10 digit number')
        return self.cleaned_data['mobile_no']

class SlotForm(forms.ModelForm):
    # date=forms.DateField(
    #     widget=forms.DateInput(
    #     attrs={
    #     'type':'date',
    #     }
    #     )
    # )
    class Meta:
        model = LabSlot1
        fields=['time_start',]


class Add_Test(forms.ModelForm):
    # email_id=forms.CharField(widget=forms.EmailInput)
    # profile_photo= ImageField(blank=True, manual_crop="")
    class Meta:
        model=Test1
        exclude=('user','collector',)

report/forms.py
from django import forms
from .models import Report, Item
from dal import autocomplete
from .models import LabTest

class Make_Report(forms.ModelForm):
    class Meta:
        model=Report
        fields='__all__'

class ItemForm(forms.ModelForm):
    lab_test_name = forms.ModelChoiceField(
                queryset=LabTest.objects.all(),
                widget=autocomplete.ModelSelect2(url='report:name-autocomplete',
                attrs={
                'data-placeholder': 'Test-name',
                #'data-minimum-input-length': 1,
                })
            )
    class Meta:
        model = Item
        fields = ['lab_test_name','value',]

lab1/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from .forms import SlotForm
from django.shortcuts import get_object_or_404, redirect
from django.http import HttpResponse
from django.views.generic.edit import CreateView, UpdateView, DeleteView
import datetime
from django.urls import reverse,reverse_lazy
from django.db.models import Max
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.db import IntegrityError
from django.utils.decorators import method_decorator
from .forms import Add_Profile, Modify_Profile, Add_Test
from .models import Lab1, LabSlot1, Lab_complaint_feedback,BookingDateLab, Test1
from django.http import HttpResponseRedirect
from django.utils import timezone
from tests.models import Test
from patient.models import Patient, LabBooking
from samplecollector.models import SampleCollector



def lab_home(request):
    user = request.user 
    print(user)
    profile = Lab1.objects.get(user=user)  
    fb= Lab_complaint_feedback.objects.all()   
    context={
           'profile':profile
    }
    
    return render(request, 'lab1/profile_home.html',context)


def tests(request):
    user=request.user
    test = Test1.objects.all()
    profile=Lab1.objects.get(user=user)
    context = {
        "all_test": test,
        "profile":profile,
    }
    return render(request, 'lab1/test_list.html',context=context)
    
	 
	

# Create your views here.
# def home(request):
#     username = request.user.username
#     user_instance = User.objects.get(username=username)
#     physio_instance = Physiotherapist.objects.get(user=user_instance)
#     upcoming_appointments = AppointmentPhysio.objects.filter(physiotherapist=physio_instance, status='U')
#     completed_appointments = AppointmentPhysio.objects.filter(physiotherapist=physio_instance, status='C')
#     if request.method == 'GET':
#         slot_form = SlotForm()
#         # slot_form.fields['time_start'].widget = DateTimePickerInput()
#     elif request.method == 'POST':
#         slot_form = SlotForm(request.POST)
#         if slot_form.is_valid():
#             slot_form.save()    
#     return render(request, 'physiotherapist/physiotherapist1.html',{
#         'upcoming': upcoming_appointments,
#         'completed': completed_appointments,
#         'slot_form': slot_form,
#     })




def verification(request):
    return render(request,'lab1/verification.html')

def index(request):
    user=request.user
    profile=Lab1.objects.get(user=user)
    print(profile)
    context={
           'profile':profile
    }

    return render(request,'lab1/profile_home.html', context=context)


def make_profile(request):
    user = request.user
    if request.method=="POST":   
        form=Add_Profile(request.POST, request.FILES ,initial={'user':user,'email_id':user.email})

        if form.is_valid():
            profile_item=form.save(commit=False)
            profile_item.user = user
            profile_item.verified=False
            profile_item.email_id=user.email
            profile_item.save()

            # return render(request, "physiotherapist/verification.html", {})
            return redirect('/lab1/home/')


    else:

        form=Add_Profile(initial={'user':user,'email_id':user.email})
        #form.fields['user'].widget.attrs['disabled'] = True
        #form.fields['user'].editable=False
    return render(request,'lab1/make_profile.html',{'form':form})


def modify_profile(request):
    user = request.user
    profile_item = Lab1.objects.get(user=user)
    form=Modify_Profile(request.POST or None, instance=profile_item)
    if form.is_valid():
            form.save()
            return redirect('/lab1/home/')
    return render(request,'lab1/modify_profile.html',{'form':form})


def Show_Profile(request):
        user = request.user
        profile = Lab1.objects.get(user=user) 
        context={
            'profile':profile
        }
        if(profile.verified==True):
            # print('&&')
            return render(request,'lab1/show_profile.html',context)
        else:
            # print('%%')
            return redirect(reverse('lab1:verification'))

def create_slot(request, pk):
    user=request.user
    form = SlotForm(request.POST or None)
    date = get_object_or_404(BookingDateLab, pk=pk)
    if form.is_valid():

        item = form.save(commit=False)
        item.date = date
        profile = Lab1.objects.get(user=user)
        item.physiotherapist =profile
        try:
            item.save()
        except IntegrityError as e:
            context = {
                'date': date,
                'form': form,
                'message':"*Slot already Exists"
            }
            return render(request, 'lab1/create_slot.html', context)

        return redirect('/lab1/home/')
    context = {
        'date': date,
        'form': form,
    }

    return render(request, 'lab1/create_slot.html', context)

# @method_decorator(login_url=reverse_lazy('login'))
class DateCreate(CreateView):

    model=BookingDateLab
    fields=['date',]


    def get_initial(self):

         max_date=BookingDateLab.objects.all().aggregate(Max('date'))
        #  print(max_date)
        #  print(datetime)
         if max_date['date__max'] == None:
              max_date['date__max'] = timezone.now() + datetime.timedelta(days=1)
        #  print(max_date)     
         key, value = max_date.popitem()
        #  value += datetime.timedelta(days=1)
        #  print(value)
        # value=int(list(max_id.values())[0])
        # value=value+1
        # #user = request.user
        #
        #
        # #print(value)
         initial = super(DateCreate, self).get_initial()
         initial.update({'date': value})
         return initial
    def form_valid(self, form):
        user=self.request.user

        profile = Lab1.objects.get(user=user)
        date = form.save(commit=False)
        # print(date)
        try:
            obj = BookingDateLab.objects.filter(date=str(date)).filter(lab=profile).first()
        except BookingDate.DoesNotExist:
            obj = None
        # obj=get_object_or_404(BookingDate, date=str(date))
        # print('SHIVAM')
        # print(obj)
        #print(obj.pk)
        if(obj==None):
            # print("no")
            date.physiotherapist = profile
            return super(DateCreate, self).form_valid(form)
        else:
            # print('Yes')
            #return create_slot(self.request,pk=obj.pk-1)
            return redirect(str(obj.pk) + '/slot/')
            #return reverse('doctor_profile:create_slot',kwargs={'pk':int(obj.pk)})
            #return HttpResponse('OK')
            #return super(DateCreate, self).form_invalid(form)
        # context={
        #
		#     "object":appointment,
		# }
		# return render(self.request,'booking/booking_confirmation.html', context=context)


# @login_required(login_url=reverse_lazy('login'))
def show_slots(request):
    user=request.user
    profile = Lab1.objects.get(user=user)
    first_name=profile.first_name
    last_name=profile.last_name
    dates=Slot.objects.filter(physiotherapist=profile).order_by('start_time')
    print(dates)
    return render(request,'lab1/show_slots.html',{'slots':dates,'first_name':first_name,'last_name':last_name})

class ComplaintFeedbackCreate(CreateView):

    model= Lab_complaint_feedback
    fields=['specify_type','description']


    def form_valid(self, form):
        user=self.request.user

        profile = Lab1.objects.get(user=user)
        feedback = form.save(commit=False)
        feedback.physiotherapist = profile
        feedback.save()
        return redirect('/lab1/home/')
        # print(date)
        # try:
        #     obj = BookingDate.objects.filter(date=str(date)).filter(physiotherapist=profile).first()
        # except BookingDate.DoesNotExist:
        #     obj = None
        # # obj=get_object_or_404(BookingDate, date=str(date))
        # print('SHIVAM')
        # print(obj)
        # #print(obj.pk)
        # if(obj==None):
        #     print("no")
        #     date.physiotherapist = profile
        #     return super(DateCreate, self).form_valid(form)
        # else:
        #     print('Yes')
        #     #return create_slot(self.request,pk=obj.pk-1)
        #     return redirect(str(obj.pk) + '/slots/')
            #return reverse('doctor_profile:create_slot',kwargs={'pk':int(obj.pk)})
            #return HttpResponse('OK')
            #return super(DateCreate, self).form_invalid(form)
        # context={
        #
		#     "object":appointment,
		# }
		# return render(self.request,'booking/booking_confirmation.html', context=context)
def show_complaint_feedback(request):            
    user=request.user    
    profile = Lab1.objects.get(user=user)    
    lab_owner=profile.lab_owner    
    feedback=Lab_complaint_feedback.objects.filter(lab=profile)    
    # print(feedback)     
    return render(request,'lab1/show_profile.html',{'feedbacks':feedback,'lab_owner':lab_owner,})   

def delete_slot(request, slot_id):   
    # print(request.get['slot_id'])
    Slot.objects.filter(pk=slot_id).delete()
    return redirect('/lab1/slots/')

def collected_samples(request):
    user=request.user
    lab = Lab1.objects.get(user=user)
    bookings=LabBooking.objects.filter(lab_id=lab.id).filter(status='Collected')
    if not bookings:
        context= {
            "status":"Hurray No Pending Appointments",
            "profile":lab,
            "bookings":bookings,
           
        }
    else:
        context = {
        "status":"Upcoming Appointments",
        "bookings":bookings,
        "profile":lab,
        }
    return render(request,'lab1/collected_samples1.html',context=context)

def reports(request):
    user=request.user
    lab = Lab1.objects.get(user=user)
    bookings=LabBooking.objects.filter(lab_id=lab.id).filter(status='Completed')
    if not bookings:
        context= {

lab1/templates/lab1/new_file.html
<form method="POST" action="">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="save">
</form>

lab1/templates/lab1/profile_home.html
{% extends 'base.html' %}

{% load static %}

{% block lab_homepage %}
<script>
{% comment %} function relocate_edit()
{
     location.href = "/profile/modify_profile";
}

function relocate_appointment()
{
     location.href = "/appointments/";
}
function relocate_slots()
{
     location.href = "/profile/date_add/";
}
</script> {% endcomment %}
</script>


<!-- NAV BAR -->
      <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
      <div class="container">
        <a href='' class="navbar-brand"><b>HEAL AT HOME</b></a>
        <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a href='' class="nav-link">Home</a>
            </li>


           
            <li class="nav-item active">
              <a href='' class="nav-link">Logout</a>
            </li> 
          </ul>
        </div>
      </div>
    </nav>
    <style>
  		.checked{
  			color: orange;
  		}
  		.button {
		    border: none;
		    color: black;
		    background-color: #edecea;
		    padding: 15px 25px;
		    text-align: center;
		    text-decoration: none;
		    display: inline-block;
		    font-size: 20px;
		    margin: 4px 2px;
		    cursor: pointer;
		}
		.card{
    box-shadow: 0 16px 48px #E3E7EB;
    }

	.card1{
    box-shadow: #E3E7EB;
    }
		.button:hover{
			background-color: rgb(244, 173, 66);
			color: white;
		}
		td{
			padding:15px 45px;
			font-size: 17px;
		}
		.heading_btn{
			padding:15px 45px;
			font-size: 20px;
			cursor: pointer;
		}
		.heading_btn:hover{
			background-color: rgb(244, 173, 66);
		}

  	</style>


<div class="container" style="margin-top: 5%">
		<div class="row">
			<div class="col-md-2">
				<br>
				<div>
					<img src="/media/{{profile.profile_photo}}" class="img-rounded" alt="DOCTOR" width="200" height="236"> 
				</div>

				<br>

            

			</div>
			<div class="col-md-10 col-sm-offset-1">
				<div class="col-xs-8 text-left" style='padding: 15px 45px'>
					<span style="font-size: 35px; ">{{profile.lab_name}}</span>&nbsp&nbsp&nbsp
					<span style="font-size: 15px; "><a href="{% url 'lab1:lab_modify_profile'  %}">Edit Profile</a></span>&nbsp&nbsp&nbsp

				</div>
				<div style="margin-top: 7px;color: blue;font-size: 20px; padding: 1px 45px" >
					{{profile.lab_name}}
				</div>

          <br><br>
			    <div class="btn-group btn-group-md card1" style='padding: 2px 45px'>
				    <!-- <button class="button button1">Send Message</button> -->
            
					<a href="{% url 'lab1:lab_show_tests'  %}" class="button button3" role="button">View Tests</a>
					<a href="{% url 'lab1:lab_assign_collector'  %}" class="button button3" role="button">Add Sample Collector</a>
					<a href="{% url 'lab1:lab_collected_samples'  %}" class="button button3" role="button">Collected Samples</a>
					<a href="{% url 'lab1:lab_reports' %}" class="button button3" role="button">Reports</a>

			

				    {% comment %} <!-- <button class="button button2" href="#contact"> Contact</button> -->
				    <butoon class="button button3" onclick=" relocate_edit()">Edit</butoon>
            <butoon class="button button3" onclick=" relocate_appointment()">Show Appointments</butoon>
            <butoon class="button button3" onclick=" relocate_slots()">Make Slot</butoon> {% endcomment %}
			    </div>

			    	<br><br>


          <div style='padding: 0px 45px' >
          <hr>
          </div>
			    	<br>

			    <!-- <div style="display: none;" id="Experience">
			    	<span style="font-size: 17px;">Doctors's experience will be here.</span>
			    </div> --><div class="card">
				<div >
			    	<div style="padding: 5px 45px;font-size: 16px;opacity: 0.5;">
			    		LAB BASIC INFORMATION
			    	</div><br>
			    	
			    		<table>
			    			<tr>
			    				<td>Lab Owner</td>
			    				<td>{{profile.lab_owner}}</td>
			    			</tr>
			    			<tr>
			    				<td>Lab Registration</td>
			    				<td>{{profile.lab_registration}}</td>
			    			</tr>
			    		</table>
					</div><br>
					
				
			    	<div style="padding: 15px 45px;font-size: 16px;opacity: 0.5;">
              <a name="contact"></a>
			    		CONTACT INFORMATION
			    	</div><br>
			    	<table>
                        <tr>
			    			<td>House No.</td>
			    			<td>{{profile.house_no}}</td>
			    		</tr>
			    		<tr>
			    			<td>Lab Address</td>
			    			<td>{{profile.lab_address}}</td>
			    		</tr>
			    		<tr>
			    			<td>Mobile No</td>
			    			<td>{{profile.mobile_no}}</td>
			    		</tr>
              <tr>
			    			<td>City</td>
			    			<td>{{profile.city}}</td>
			    		</tr>
			    		<tr>
			    			<td>State</td>
			    			<td>{{profile.state}}</td>
                        </tr>
                        <tr>
			    			<td>Pin</td>
			    			<td>{{profile.pin}}</td>
                        </tr>
                        <tr>
			    			<td>Rating</td>
			    			<td>{{profile.rating}}</td>
			    		</tr>

			    	</table>
			    </div>
			</div>
		</div>
	</div>
</div>
<br><br><br><br>


{% endblock %}

lab1/templates/lab1/test_list.html
{% extends 'base.html' %}

{% load static %}
{% load widget_tweaks %}

{% block test_list %}
<script>
{% comment %} function relocate_edit()
{
     location.href = "/profile/modify_profile";
}

function relocate_appointment()
{
     location.href = "/appointments/";
}
function relocate_slots()
{
     location.href = "/profile/date_add/";
}
</script> {% endcomment %}
</script>
<!-- NAV BAR -->
      <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
      <div class="container">
        <a href='' class="navbar-brand"><b>HEAL AT HOME</b></a>
        <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a href='' class="nav-link">Home</a>
            </li>


           
            <li class="nav-item active">
              <a href='' class="nav-link">Logout</a>
            </li> 
          </ul>
        </div>
      </div>
    </nav>
    <style>
  		.checked{
  			color: orange;
  		}
  		.button {
		    border: none;
		    color: black;
		    background-color: #edecea;
		    padding: 15px 25px;
		    text-align: center;
		    text-decoration: none;
		    display: inline-block;
		    font-size: 20px;
		    margin: 4px 2px;
		    cursor: pointer;
		}
		.button:hover{
			background-color: rgb(244, 173, 66);
			color: white;
		}
		td{
			padding:15px 45px;
			font-size: 17px;
		}
		.heading_btn{
			padding:15px 45px;
			font-size: 20px;
			cursor: pointer;
		}
		.heading_btn:hover{
			background-color: rgb(244, 173, 66);
		}

  	</style>


<div class="container" style="margin-top: 5%">
		<div class="row">
			<div class="col-md-2">
				<br>
				<div>
					<img src="/media/{{profile.profile_photo}}" class="img-rounded" alt="DOCTOR" width="200" height="236"> 
				</div>

				<br>

            

			</div>
			<div class="col-md-10 col-sm-offset-1">
				<div class="col-xs-8 text-left" style='padding: 15px 45px'>
					<span style="font-size: 35px; ">{{profile.lab_name}}</span>&nbsp&nbsp&nbsp
					<span style="font-size: 15px; "><a href="{% url 'lab1:lab_modify_profile'  %}">Edit Profile</a></span>&nbsp&nbsp&nbsp

				</div>
				<div style="margin-top: 7px;color: blue;font-size: 20px; padding: 1px 45px" >
					{{profile.lab_name}}
				</div>

          <br><br>
			    <div class="btn-group btn-group-md" style='padding: 2px 45px'>
				    <!-- <button class="button button1">Send Message</button> -->
            
			<a href="{% url 'lab1:lab_show_tests'  %}" class="button button3" role="button">View Tests</a>
			<a href="{% url 'lab1:lab_assign_collector'  %}" class="button button3" role="button">Add Sample Collector</a>
			<a href="{% url 'lab1:lab_collected_samples'  %}" class="button button3" role="button">Collected Samples</a>
			<a href="{% url 'lab1:lab_reports' %}" class="button button3" role="button">Reports</a>

			

				    {% comment %} <!-- <button class="button button2" href="#contact"> Contact</button> -->
				    <butoon class="button button3" onclick=" relocate_edit()">Edit</butoon>
            <butoon class="button button3" onclick=" relocate_appointment()">Show Appointments</butoon>
            <butoon class="button button3" onclick=" relocate_slots()">Make Slot</butoon> {% endcomment %}
			    </div>

			    	<br><br>


          <div style='padding: 0px 45px'>
          <hr>
          </div>
			    	<br>

			    <!-- <div style="display: none;" id="Experience">
			    	<span style="font-size: 17px;">Doctors's experience will be here.</span>
			    </div> -->

			    	<div style="padding: 15px 45px;font-size: 16px;opacity: 0.5;">
			    		LAB TESTs AVAILABLE
			    	</div><br>
			    	<div class="container">
                        <div class="row">
                            {% for test in all_test %}
                    
                    <div class="col-md-3 medicine_hover">
                      <div class="card medicine_1" style="text-align: center;border: none;">
                        <img class="card-img-top img_list" src="/media/{{test.photo}}" alt="{{test.name}}" style="width:2300; height:200px;">
                        <div class="card-body">
                          <h4 class="card-title">{{test.name}}</h4>
                          
                          <p class="card-text">
                            <i><span style="font-size: 10px;">by <a href="#">{{test.test_type}}{{test.test_type}}</a></span></i><br>
                            <span style="color: red;"><i class="fa fa-rupee" style="font-size: 14px;"></i><s>{{ test.price }}</s></span>
                           <span style="color: red;"><i class="fa fa-rupee" style="font-size: 14px;"></i>{{ test.discounted_price }}</span>
                           
                          </p>
                        </div>
                      </div>
                      <br>  
                    </div>
                    
                            {% endfor %}
                        </div>
                    </div> 
			    	
			    	
			    </div>
			</div>
		</div>
	</div>

<br><br><br><br>


{% endblock %}