api/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('physio/get/', api_get_physio.as_view()),
    path('nurse/get/', api_get_nurse.as_view()),
    path('patient/get/', api_get_patient.as_view()),
    path('report/get/', api_get_report.as_view()),
    path('test/get/', api_get_test.as_view()),
    path('test/get/<int:id>', api_get_test_one.as_view()),
    path('test/create', api_create_test.as_view()),
    ]

heal/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from accounts.views import index
from .views import home_page
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    path('nurse/', include('nurse.urls')),
    path('patient/', include('patient.urls')),
    path('report/', include('report.urls')),
    url('',include('adminpage.urls')),
    path('', home_page),
    path('physiotherapist/',include('physiotherapist.urls')),
    path('lab1/',include('lab1.urls')),
    path('samplecollector/',include('samplecollector.urls')),
    path('blog/', include('blog.urls')),
    path('api/', include('api.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

lab1/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from .views import *



app_name='lab1'

urlpatterns = [
    path('',views.index,name='index'),
    path('make_profile/',views.make_profile,name='lab_make_profile'),
    path('add_test/',views.add_test,name='add_test'),
    path('modify_profile/',views.modify_profile,name='lab_modify_profile'),
    path('show_profile/',views.Show_Profile,name='lab_show_profile'),
    path('show_tests/',views.tests, name='lab_show_tests'),
    path('lab_bookings/',views.show_bookings, name='lab_show_bookings'),
    path('assign_collector/',views.assign_collector, name='lab_assign_collector'),
    path('collected_samples/',views.collected_samples, name='lab_collected_samples'),
    path('reports/',views.reports, name='lab_reports'),
    path('home/', lab_home, name='lab_home'),
    path('date_add/',views.DateCreate.as_view(),name='lab_date_create'),
    url(r'^date_add/(?P<pk>[0-9]+)/slot/$', views.create_slot, name='lab_create_slot'),
    path('slots/',views.show_slots,name='show_slots'),
    path('complaint_feedback/', views.ComplaintFeedbackCreate.as_view(template_name="lab1/new_file.html"), name='lab_complaint_feedback'),
    path('show_complaint_feedback/', views.show_complaint_feedback, name='lab_show_complaint_feedback'),
    url(r'^delete_slot/(?P<slot_id>[0-9]+)$',views.delete_slot,name='lab_delete_slot'),
    url(r'^select_collector/(?P<pk>[0-9]+)$',views.select_collector,name='select_collector'),
    url(r'^assign_collector_to_test/(?P<collector_id>\w+)/(?P<booking_id>\w+)/$',views.assign_collector_to_test,name='assign_collector_to_test'),
    ]

physiotherapist/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from .views import *



app_name='physiotherapist'

urlpatterns = [
    path('',views.index,name='index'),
    # path('slot/', views.home),
    path('make_profile/',views.make_profile,name='make_profile'),
    path('modify_profile/',views.modify_profile,name='modify_profile'),
    path('show_profile/',views.Show_Profile,name='show_profile'),
    path('home/', physio_home, name='home'),
    path('date_add/',views.DateCreate.as_view(),name='Date_Create'),
    url(r'^date_add/(?P<pk>[0-9]+)/slot/$', views.create_slot, name='create_slot'),
    path('slots/',views.show_slots,name='show_slots'),
    path('complaint_feedback/', views.ComplaintFeedbackCreate.as_view(), name='complaint_feedback'),
    path('show_complaint_feedback/', views.show_complaint_feedback, name='show_complaint_feedback'),
    url(r'^delete_slot/(?P<slot_id>[0-9]+)$',views.delete_slot,name='delete_slot'),
    path('appointments/',views.show_appointments,name='show_appointments'),
    path('work_history/',views.work_history,name='work_history'),
    # path('attend_appointment',views.show_slots,name='show_slots'),
    url(r'^attend_appointment/(?P<appointment_id>[0-9]+)$',views.attend_appointment,name='attend_appointment'),
    ]

report/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name='report'

urlpatterns=[
    path('',views.index,name='index'),
    # url(r'^prescription_add/(?P<appointment_id>[0-9]+)$',views.PrescriptionCreate.as_view(),name='Prescription_Add1'),
    url(r'^report_add/(?P<booking_id>[0-9]+)$',views.ReportCreate.as_view(),name='Report_Add1'),
    # path('prescription_add/',views.make_prescription,name='Prescription_Add'),
    url(r'^(?P<pk>[0-9]+)/$',views.DetailView.as_view(),name='detail'),
    url(r'^(?P<report_id>[0-9]+)/create_item/$', views.create_item, name='create_item'),
    path('name-autocomplete/',views.LabTestAutocomplete.as_view(),name='name-autocomplete'),
    url(r'^(?P<report_id>[0-9]+)/print/$', views.print, name='print'),

]

samplecollector/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from .views import *



app_name='samplecollector'

urlpatterns = [
    path('',views.sample_collector_home,name='collector_home'),
    path('make_profile/',views.make_profile,name='collector_make_profile'),
    path('modify_profile/',views.modify_profile,name='collector_modify_profile'),
    path('assigned_samples/',views.samples_to_be_collected, name='collector_assigned_samples'),
    path('collected_samples/',views.collected_samples, name='collector_collected_samples'),
    url(r'^confirm_collection/(?P<booking_id>\w+)/$',views.confirm_collection,name='confirm_collection'),
    url(r'^collection_details/(?P<booking_id>\w+)/$',views.collection_details,name='collector_collection_details'),
    url(r'^collector_collected_details/(?P<booking_id>\w+)/$',views.collector_collected_details,name='collector_collected_details'),
    
    
    ]

report/forms.py
from django import forms
from .models import Report, Item
from dal import autocomplete
from .models import LabTest

class Make_Report(forms.ModelForm):
    class Meta:
        model=Report
        fields='__all__'

class ItemForm(forms.ModelForm):
    lab_test_name = forms.ModelChoiceField(
                queryset=LabTest.objects.all(),
                widget=autocomplete.ModelSelect2(url='report:name-autocomplete',
                attrs={
                'data-placeholder': 'Test-name',
                #'data-minimum-input-length': 1,
                })
            )
    class Meta:
        model = Item
        fields = ['lab_test_name','value',]

report/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404, redirect
from .models import Report, LabTest
from .models import Item
from django.http import HttpResponse
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import View
from .forms import Make_Report, ItemForm
from django.views import generic
from django.db.models import Max
from dal import autocomplete
from .utils import render_to_pdf
from django.template.loader import get_template
from io import BytesIO
from django.core.files import File
# from doctor_profile.models import Profile
from django.views.generic import FormView, CreateView
# from booking.models import AppointmentDetials
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from pprint import pprint
# Create your views here.
from django.contrib.auth.models import User
import time
from lab1.models import Lab1
from patient.models import LabBooking
from pprint import pprint

def index(request):
    return render(request,'report/report_home.html')

# @login_required(login_url=reverse_lazy('login'))
# def make_prescription(request):
#     if request.method=="POST":
#         form=Make_Report(request.POST)
#         if form.is_valid():
#             profile_item=form.save(commit=False)
#             profile_item.save()
#             #return redirect('/profile/show_profile/'+str(profile_item.doctor_id))
#     else:
#         form=Make_Prescription()
#     return render(request,'new_file.html',{'form':form})

class DetailView(generic.DetailView):
    model=Report
     
    template_name='report/detail.html'


class ReportCreate(CreateView):


    model=Report
    fields=['report_id',]
#################################TO PASS INITIAL VALUES ############
    def get_initial(self):
        booking_id=self.kwargs['booking_id']
        max_id=Report.objects.all().aggregate(Max('report_id'))
        if list(max_id.values())[0] == None:
            value=0
        else:
            value=int(list(max_id.values())[0])
        value=value+1
        #user = request.user


        #print(value)
        booking_id=self.kwargs['booking_id']
        initial = super(ReportCreate, self).get_initial()
        initial.update({'report_id': value})
        pprint('*')
        return initial

    def get_context_data(self, **kwargs):
        context = super(ReportCreate, self).get_context_data(**kwargs)
        user = self.request.user
        lab = Lab1.objects.get(user=user)
        booking = LabBooking.objects.get(id=self.kwargs['booking_id'])
        context['booking']= booking
        context['lab']= lab
        pprint(context)
        return context



    def form_valid(self, form):
        #event = Event.objects.get(pk=self.kwargs['appointment_id'])
        user=self.request.user
        lab = Lab1.objects.get(user=user)
        booking_id=int(self.kwargs['booking_id'])

        #print('**')
        report = form.save(commit=False)

        report.lab = Lab1.objects.get(user=user)
        report=form.save()
        booking = LabBooking.objects.get(id=self.kwargs['booking_id'])
        booking.status = 'Completed'
        booking.report = report
        booking.save()
        return super(ReportCreate, self).form_valid(form)

# @login_required(login_url=reverse_lazy('login'))
def detail(request, pk):
    report = get_object_or_404(Report, pk=pk)
    return render(request, 'report/detail.html', {'report':report,'report_id':pk})

# @login_required(login_url=reverse_lazy('login'))
def create_item(request, report_id):
    form = ItemForm(request.POST or None, request.FILES or None , initial={'report':report_id})
    report = get_object_or_404(Report, pk=report_id)
    if form.is_valid():
        report_items = report.item_set.all()
        pprint(type(form.cleaned_data['lab_test_name']))
        for s in report_items:
            if s.lab_test_name == form.cleaned_data.get("lab_test_name").name :
                # print('**')
                context = {
                    'report': report,
                    'form': form,
                    'error_message': 'You already added that Test',
                }
                return render(request, 'report/create_item.html', context)
        item = form.save(commit=False)
        # print(item)
        lab_test = LabTest.objects.get(name=item.lab_test_name)
        item.lab_test = lab_test
        item.report = report
        item.save()
        return render(request, 'report/detail.html', {'report': report})
    context = {
        'report': report,
        'form': form,
    }
    return render(request, 'report/create_item.html', context)


class LabTestAutocomplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        qs = LabTest.objects.all()

        if self.q:
            qs = qs.filter(name__istartswith=self.q)
        #print(qs)
        return qs


def print(request,report_id):
    report = get_object_or_404(Report, pk=report_id)
    report_no=int(report_id)
    report_no=report_no 

    template=get_template('report/print.html')
    context={"report_id":str(report_no),"report":report}
    html=template.render(context)
    pdf=render_to_pdf('report/print.html',context)
    filename ="report{}.pdf".format(report_id)

    if pdf:
        report.pdf.save(filename,File(BytesIO(pdf.content)))
        return HttpResponse(pdf,content_type='application/pdf')
       

    return HttpResponse('NOT FOUND')    

samplecollector/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404, redirect
from django.http import HttpResponse
from django.views.generic.edit import CreateView, UpdateView, DeleteView
import datetime
from django.urls import reverse,reverse_lazy
from django.db.models import Max
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.db import IntegrityError
from django.utils.decorators import method_decorator
from django.http import HttpResponseRedirect
from django.utils import timezone
from tests.models import Test
from patient.models import Patient, LabBooking
from .models import *
from .forms import *
from lab1.models import Lab1



def sample_collector_home(request):
    user = request.user 
    print(user)
    profile = SampleCollector.objects.get(user=user)  
    context={
           'profile':profile
    }
    
    return render(request, 'samplecollector/profile_home.html',context)


def make_profile(request):
    user = request.user
    if request.method=="POST":   
        form=Add_Profile(request.POST, request.FILES ,initial={'user':user,})

        if form.is_valid():
            profile_item=form.save(commit=False)
            profile_item.user = user
            profile_item.save()

            # return render(request, "physiotherapist/verification.html", {})
            return redirect('/samplecommector/')


    else:

        form=Add_Profile(initial={'user':user,})
        #form.fields['user'].widget.attrs['disabled'] = True
        #form.fields['user'].editable=False
    return render(request,'samplecollector/make_profile.html',{'form':form})


def modify_profile(request):
    user = request.user
    profile_item = SampleCollector.objects.get(user=user)
    form=Modify_Profile(request.POST or None, instance=profile_item)
    if form.is_valid():
            form.save()
            return redirect(reverse('samplecollector:collector_home'))
    return render(request,'samplecollector/modify_profile.html',{'form':form})



def samples_to_be_collected(request):
    user=request.user
    samplecollector = SampleCollector.objects.get(user=user)
    bookings=LabBooking.objects.filter(collector_id=samplecollector.id).filter(status='Sampled')
    if not bookings:
        context= {
            "status":"Hurray No Pending Work",
            "profile":samplecollector,
            "bookings":bookings,
           
        }
    else:
        context = {
        "status":"Upcoming Pickups",
        "bookings":bookings,
        "profile":samplecollector,
        }
    return render(request,"samplecollector/assigned_samples.html",context=context)

def collected_samples(request):
    user=request.user
    samplecollector = SampleCollector.objects.get(user=user)
    bookings=LabBooking.objects.filter(collector_id=samplecollector.id).filter(status='Collected')
    if not bookings:
        context= {
            "status":"Samples Not Collected Yet",
            "profile":samplecollector,
            "bookings":bookings,
           
        }
    else:
        context = {
        "status":"Upcoming Pickups",
        "bookings":bookings,
        "profile":samplecollector,
        }
    return render(request,"samplecollector/collected_samples.html",context=context)



def collection_details(request, booking_id):
    user=request.user
    booking = LabBooking.objects.get(pk=booking_id)
    patient_id=booking.patient.id
    lab_id=booking.lab.id
    patient_object=Patient.objects.get(pk=patient_id)
    lab_object=Lab1.objects.get(pk=patient_id)
    print(patient_id)
    context= {
            "booking":booking,
            "patient_object":patient_object,
            "lab_object":lab_object,

        }
   
    return render(request,'samplecollector/collection_details.html',context=context)




def confirm_collection(request, booking_id):
    user=request.user
    bookings = LabBooking.objects.get(pk=booking_id)
    bookings.status="Collected"
    bookings.save()
    context= {
            "status":"Hurray No Pending Appointments",
            "bookings":bookings,
        }
   
    return redirect(reverse('samplecollector:collector_assigned_samples'))

def collector_collected_details(request, booking_id):
    user=request.user
    booking = LabBooking.objects.get(pk=booking_id)
    patient_id=booking.patient.id
    lab_id=booking.lab.id
    patient_object=Patient.objects.get(pk=patient_id)
    lab_object=Lab1.objects.get(pk=patient_id)
    print(patient_id)
    context= {
            "booking":booking,
            "patient_object":patient_object,
            "lab_object":lab_object,

        }
   
    return render(request,'samplecollector/collector_collected_details.html',context=context)


# def add_test(request):collector_collected_details
#     user = request.user
#     profile=Lab1.objects.get(user=user)
#     if request.method=="POST":   
#         form=Add_Test(request.POST, request.FILES ,initial={'user':user,})

#         if form.is_valid():
#             profile_item=form.save(commit=False)
#             profile_item.user = user
#             profile_item.save()

#             # return render(request, "physiotherapist/verification.html", {})
#             return redirect('/lab1/home/')


#     else:

#         form=Add_Test(initial={'user':user,})
#         context = {
#             "profile":profile,
#             "form":form,
#         }
#     return render(request,'lab1/add_test.html',context=context)

samplecollector/templates/samplecollector/add_test.html
{% extends 'base.html' %}

{% load static %}
{% load widget_tweaks %}

{% block add_test %}
<script>
{% comment %} function relocate_edit()
{
     location.href = "/profile/modify_profile";
}

function relocate_appointment()
{
     location.href = "/appointments/";
}
function relocate_slots()
{
     location.href = "/profile/date_add/";
}
</script> {% endcomment %}
</script>
<!-- NAV BAR -->
      <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
      <div class="container">
        <a href='' class="navbar-brand"><b>HEAL AT HOME</b></a>
        <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a href='' class="nav-link">Home</a>
            </li>


           
            <li class="nav-item active">
              <a href='' class="nav-link">Logout</a>
            </li> 
          </ul>
        </div>
      </div>
    </nav>
    <style>
  		.checked{
  			color: orange;
  		}
  		.button {
		    border: none;
		    color: black;
		    background-color: #edecea;
		    padding: 15px 25px;
		    text-align: center;
		    text-decoration: none;
		    display: inline-block;
		    font-size: 20px;
		    margin: 4px 2px;
		    cursor: pointer;
		}
		.button:hover{
			background-color: rgb(244, 173, 66);
			color: white;
		}
		td{
			padding:15px 45px;
			font-size: 17px;
		}
		.heading_btn{
			padding:15px 45px;
			font-size: 20px;
			cursor: pointer;
		}
		.heading_btn:hover{
			background-color: rgb(244, 173, 66);
		}

  	</style>


<div class="container" style="margin-top: 5%">
		<div class="row">
			<div class="col-md-2">
				<br>
				<div>
					<img src="/media/{{profile.profile_photo}}" class="img-rounded" alt="DOCTOR" width="200" height="236"> 
				</div>

				<br>

            

			</div>
			<div class="col-md-10 col-sm-offset-1">
				<div class="col-xs-8 text-left" style='padding: 15px 45px'>
					<span style="font-size: 35px; ">{{profile.lab_name}}</span>&nbsp&nbsp&nbsp
					<span style="font-size: 15px; "><a href="{% url 'lab1:lab_modify_profile'  %}">Edit Profile</a></span>&nbsp&nbsp&nbsp

				</div>
				<div style="margin-top: 7px;color: blue;font-size: 20px; padding: 1px 45px" >
					{{profile.lab_name}}
				</div>

          <br><br>
			    <div class="btn-group btn-group-md" style='padding: 2px 45px'>
				    <!-- <button class="button button1">Send Message</button> -->
            <a href="" class="button button3" role="button">Add Test</a>
			<a href="{% url 'lab1:lab_show_tests'  %}" class="button button3" role="button">View Tests</a>
			<a href="#contact" class="button button3" role="button">Bookings</a>
			<a href="#contact" class="button button3" role="button">Add Sample Collector</a>

			

				    {% comment %} <!-- <button class="button button2" href="#contact"> Contact</button> -->
				    <butoon class="button button3" onclick=" relocate_edit()">Edit</butoon>
            <butoon class="button button3" onclick=" relocate_appointment()">Show Appointments</butoon>
            <butoon class="button button3" onclick=" relocate_slots()">Make Slot</butoon> {% endcomment %}
			    </div>

			    	<br><br>


          <div style='padding: 0px 45px'>
          <hr>
          </div>
			    	<br>

			    <!-- <div style="display: none;" id="Experience">
			    	<span style="font-size: 17px;">Doctors's experience will be here.</span>
			    </div> -->

			    	<div style="padding: 15px 45px;font-size: 16px;opacity: 0.5;">
			    		ADD TEST
			    	</div><br>
			    	<div class="container">
                        <div class="row">
                            <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                  
                                Name :{{ form.name | add_class:"form-control" }}
                                
                                House No :{{ form.house_no  | add_class:"form-control" }}
                                Condition :{{ form.condition  | add_class:"form-control"}}
                                Test Type :{{ form.test_type  | add_class:"form-control"}}
                                Pre Test Information :{{ form.pre_test_information  | add_class:"form-control"}}
                                Description :{{ form.description | add_class:"form-control"}}
                                Price :{{ form.price | add_class:"form-control"}}
                                Discounted Price :{{ form.discounted_price | add_class:"form-control"}}
                  
                  
                                    <button type="submit" class="btn btn-dark form-control">Submit</button>
                  
                  
                            </form>
                           
                           
        
                        </div>
                    </div> 
			    	
			    	
			    </div>
			</div>
		</div>
	</div>

<br><br><br><br>


{% endblock %}

samplecollector/templates/samplecollector/assign_collector.html
{% extends 'base.html' %}


{% load static %}

<!-- <!DOCTYPE html>
<html lang="en">
<head>
  <title>Prescription</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
   -->
  {% block collected_samples %}

     <!-- NAV BAR -->
     <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
      <div class="container">
        <a href='/' class="navbar-brand"><b>HEAL AT HOME</b></a>
        <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a href='{% url "lab1:index" %}'  class="nav-link">Home</a>
			</li>
			<li class="nav-item">
				<!-- <a href='{% url "physiotherapist:modify_profile" %}'  class="nav-link">Edit Profile</a> -->
			  </li>
			<li class="nav-item">
				<a href=''  class="nav-link">Bookings</a>
			  </li>
			
			  <li class="nav-item">
				<!-- <a href='/physiotherapist/show_complaint_feedback/'  class="nav-link">Show complaints/feedback</a> -->
			  </li>
			

           
            <li class="nav-item active">
              <a href='' class="nav-link">Logout</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  <div class="container">
          <div class="col-sm-12 col-md-12">

              <div class="panel panel-default">
                  <div class="panel-body">
                    <br>
                    <!-- <h3>Dr. {{first_name}}  {{last_name}}   -->
                      <span style="color: blue;font-size: 20px; padding: 1px 45px" >
                      SELECT COLLECTOR
                      </span>
                      </h3> 
                     
                      <br>
                      {% if error_message %}
                          <p><strong>{{ error_message }}</strong></p>
                      {% endif %}
                      

                    
                        <table class="table table-striped table-hover ">
                            <thead class="thead-light">
                                <tr>
                                  <th>Booking Id    </th>
                                  <th>Date of booking</th>
                                  <th>Paitent Name</th>
                                  <th>Test Name</th>
                                  <th>Link</th>
                                </tr>
                              </thead>
                              <tbody>
                            
                        
                        {% for booking in bookings %}
                        <tr>
                            <th scope="row">{{booking.id}}</th>
                            <td>{{booking.date}}</td>
                            <td>{{booking.patient}}</td>
                            <td>{{booking.test}}</td>
                            <td><a href="{% url 'lab1:select_collector' booking.id %}">Select Collector</a></td>
                        
                          </tr>
                         
                
                        {% endfor %} 
                        </tbody>
                    </table>

                  </div>
              </div>

          </div>

      </div>


      </br></br></br></br></br></br></br></br></br></br></br></br></br></br>
      {% endblock %}

</body>
</html>

samplecollector/templates/samplecollector/create_item_template.html
{% for field in form %}
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <span class="text-danger small">{{field.errors}}</span>
    </div>

    <label class="control-label col-sm-3 text-right">{{ field.label_tag}}</label>
    <label class="col-sm-5 text-left">{{ field }}</label>
  </div>
{% endfor %}

samplecollector/templates/samplecollector/date-template.html
{% for field in form %}
  <div class="form-group ">
    <div class="col-sm-offset-2 col-sm-10">
      <span class="text-danger small">{{field.errors}}</span>
    </div>
    <label class="control-label col-sm-3">{{ field.label_tag}}</label>
    <label class="col-sm-8">{{ field }}</label>
  </div>
{% endfor %}

samplecollector/templates/samplecollector/new_file.html
<form method="POST" action="">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="save">
</form>

samplecollector/templates/samplecollector/reports.html
{% extends 'base.html' %}


{% load static %}

<!-- <!DOCTYPE html>
<html lang="en">
<head>
  <title>Prescription</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
   -->
  {% block collected_samples %}

     <!-- NAV BAR -->
     <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
      <div class="container">
        <a href='/' class="navbar-brand"><b>HEAL AT HOME</b></a>
        <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a href='{% url "lab1:index" %}'  class="nav-link">Home</a>
			</li>
			<li class="nav-item">
				<!-- <a href='{% url "physiotherapist:modify_profile" %}'  class="nav-link">Edit Profile</a> -->
			  </li>
			<li class="nav-item">
				<a href=''  class="nav-link">Bookings</a>
			  </li>
			
			  <li class="nav-item">
				<!-- <a href='/physiotherapist/show_complaint_feedback/'  class="nav-link">Show complaints/feedback</a> -->
			  </li>
			

           
            <li class="nav-item active">
              <a href='' class="nav-link">Logout</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  <div class="container">
          <div class="col-sm-12 col-md-12">

              <div class="panel panel-default">
                  <div class="panel-body">
                    <br>
                    <!-- <h3>Dr. {{first_name}}  {{last_name}}   -->
                      <span style="color: blue;font-size: 20px; padding: 1px 45px" >
                       REPORTS
                      </span>
                      </h3> 
                     
                      <br>
                      {% if error_message %}
                          <p><strong>{{ error_message }}</strong></p>
                      {% endif %}
                      

                    
                        <table class="table table-striped table-hover ">
                            <thead class="thead-light">
                                <tr>
                                  <th>Booking Id    </th>
                                  <th>Date of booking</th>
                                  <th>Paitent Name</th>
                                  <th>Test Name</th>
                                  <th>Report Link</th>
                                </tr>
                              </thead>
                              <tbody>
                            
                        
                        {% for booking in bookings %}
                        <tr>
                            <th scope="row">{{booking.id}}</th>
                            <td>{{booking.date}}</td>
                            <td>{{booking.patient}}</td>
                            <td>{{booking.test}}</td>
                            <td><a href="{% url 'lab1:select_collector' booking.id %}">View Report</a></td>
                        
                          </tr>
                         
                
                        {% endfor %} 
                        </tbody>
                    </table>

                  </div>
              </div>

          </div>

      </div>


      </br></br></br></br></br></br></br></br></br></br></br></br></br></br>
      {% endblock %}

</body>
</html>