api/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('physio/get/', api_get_physio.as_view()),
    path('nurse/get/', api_get_nurse.as_view()),
    path('patient/get/', api_get_patient.as_view()),
    path('report/get/', api_get_report.as_view()),
    path('test/get/', api_get_test.as_view()),
    path('test/get/<int:id>', api_get_test_one.as_view()),
    path('test/create', api_create_test.as_view()),
    ]

heal/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from accounts.views import index
from .views import home_page
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),
    path('nurse/', include('nurse.urls')),
    path('patient/', include('patient.urls')),
    path('report/', include('report.urls')),
    url('',include('adminpage.urls')),
    path('', home_page),
    path('physiotherapist/',include('physiotherapist.urls')),
    path('lab1/',include('lab1.urls')),
    path('samplecollector/',include('samplecollector.urls')),
    path('blog/', include('blog.urls')),
    path('api/', include('api.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

nurse/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from .views import *



app_name='nurse'

urlpatterns = [
    path('',views.index,name='index'),
    # path('slot/', views.home),
    path('make_profile/',views.make_profile,name='make_profile'),
    path('modify_profile/',views.modify_profile,name='modify_profile'),
    path('show_profile/',views.Show_Profile,name='show_profile'),
    path('home/', physio_home, name='home'),
    path('date_add/',views.DateCreate.as_view(),name='Date_Create'),
    url(r'^date_add/(?P<pk>[0-9]+)/slot/$', views.create_slot, name='create_slot'),
    path('slots/',views.show_slots,name='show_slots'),
    path('complaint_feedback/', views.ComplaintFeedbackCreate.as_view(), name='complaint_feedback'),
    path('show_complaint_feedback/', views.show_complaint_feedback, name='show_complaint_feedback'),
    url(r'^delete_slot/(?P<slot_id>[0-9]+)$',views.delete_slot,name='delete_slot'),
    
    path('appointments/',views.show_appointments,name='show_appointments'),
    path('work_history/',views.work_history,name='work_history'),
    # path('attend_appointment',views.show_slots,name='show_slots'),
    url(r'^attend_appointment/(?P<appointment_id>[0-9]+)$',views.attend_appointment,name='attend_appointment'),
    ]

nurse/forms.py
from django.forms import ModelForm
from django import forms
from .models import Slot, Nurse

# class SlotForm(ModelForm):
#     class Meta:
#         model = Slot
#         fields = ['time_start', 'time_end']
        # widgets = {
        #      'time_start': DatePickerInput(), # default date-format %m/%d/%Y will be used
        #      'time_end': DatePickerInput(format='%Y-%m-%d'), # specify date-frmat
        #  }

# from pyuploadcare.dj.models import ImageField
class Add_Profile(forms.ModelForm):

    # email_id=forms.CharField(widget=forms.EmailInput)
    dob=forms.DateField(
        widget=forms.DateInput(
        attrs={
        'type':'date',
        }
        )
    )
#     user = forms.CharField(
#     widget=forms.TextInput(attrs={'readonly':'readonly'})
# )
    class Meta:
        model=Nurse
        exclude = ('user','verified','email_id',)

    def clean_mobile_no(self):
        mobile_no = self.cleaned_data['mobile_no']
        if len(str(mobile_no)) != 10:
            raise forms.ValidationError('enter  a 10 digit number')
        return self.cleaned_data['mobile_no']

class Modify_Profile(forms.ModelForm):
    # email_id=forms.CharField(widget=forms.EmailInput)
    # profile_photo= ImageField(blank=True, manual_crop="")
    class Meta:
        model=Nurse
        exclude=('user','gender','verified','rating')


    def clean_mobile_no(self):
        mobile_no = self.cleaned_data['mobile_no']
        if len(str(mobile_no)) != 10:
            raise forms.ValidationError('enter  a 10 digit number')
        return self.cleaned_data['mobile_no']

class SlotForm(forms.ModelForm):
    # date=forms.DateField(
    #     widget=forms.DateInput(
    #     attrs={
    #     'type':'date',
    #     }
    #     )
    # )
    class Meta:
        model = Slot
        fields=['start_time',]

nurse/views.py
from django.shortcuts import render
from .models import Nurse, Slot
from django.contrib.auth.models import User
from .forms import SlotForm
from django.shortcuts import get_object_or_404, redirect
from django.http import HttpResponse
from django.views.generic.edit import CreateView, UpdateView, DeleteView
import datetime
from django.urls import reverse,reverse_lazy
from django.db.models import Max
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.db import IntegrityError
from django.utils.decorators import method_decorator
from .forms import Add_Profile, Modify_Profile
from .models import BookingDate,Slot, Nurse_complaint_feedback
from django.http import HttpResponseRedirect
from django.utils import timezone
from appointment.models import AppointmentNurse

def physio_home(request):
    user = request.user
    profile = Nurse.objects.get(user=user)
    fb= Nurse_complaint_feedback.objects.all()
    # print(fb)
    context={
           'profile':profile
    }
    
    return render(request, 'nurse/nurse.html',context)

# Create your views here.
# def home(request):
#     username = request.user.username
#     user_instance = User.objects.get(username=username)
#     physio_instance = Nurse.objects.get(user=user_instance)
#     upcoming_appointments = AppointmentPhysio.objects.filter(nurse=physio_instance, status='U')
#     completed_appointments = AppointmentPhysio.objects.filter(nurse=physio_instance, status='C')
#     if request.method == 'GET':
#         slot_form = SlotForm()
#         # slot_form.fields['time_start'].widget = DateTimePickerInput()
#     elif request.method == 'POST':
#         slot_form = SlotForm(request.POST)
#         if slot_form.is_valid():
#             slot_form.save()    
#     return render(request, 'nurse/nurse1.html',{
#         'upcoming': upcoming_appointments,
#         'completed': completed_appointments,
#         'slot_form': slot_form,
#     })




def verification(request):
    return render(request,'nurse/verification.html')

def index(request):
     #print(user)

    return render(request,'nurse/profile_home.html')


def make_profile(request):
    user = request.user
    if request.method=="POST":
        form=Add_Profile(request.POST, request.FILES ,initial={'user':user,'email_id':user.email})

        if form.is_valid():
            profile_item=form.save(commit=False)
            profile_item.user = user
            profile_item.verified=False
            profile_item.email_id=user.email
            profile_item.save()

            # return render(request, "nurse/verification.html", {})
            return redirect('/nurse/home/')


    else:

        form=Add_Profile(initial={'user':user,'email_id':user.email})
        #form.fields['user'].widget.attrs['disabled'] = True
        #form.fields['user'].editable=False
    return render(request,'nurse/new.html',{'form':form})


def modify_profile(request):
    user = request.user
    profile_item = Nurse.objects.get(user=user)
    form=Modify_Profile(request.POST or None, instance=profile_item)
    if form.is_valid():
            form.save()
            return redirect('/nurse/home/')
    return render(request,'nurse/new.html',{'form':form})


def Show_Profile(request):
        user = request.user
        profile = Nurse.objects.get(user=user)
        context={
            'profile':profile
        }
        if(profile.verified==True):
            # print('&&')
            return render(request,'nurse/show_profile.html',context)
        else:
            # print('%%')
            return redirect(reverse('nurse:verification'))

def create_slot(request, pk):
    user=request.user
    form = SlotForm(request.POST or None)
    date = get_object_or_404(BookingDate, pk=pk)
    if form.is_valid():

        item = form.save(commit=False)
        item.date = date
        profile = Nurse.objects.get(user=user)
        item.nurse =profile
        try:
            item.save()
        except IntegrityError as e:
            context = {
                'date': date,
                'form': form,
                'message':"*Slot already Exists"
            }
            return render(request, 'nurse/create_slot.html', context)

        return redirect('/nurse/home/')
    context = {
        'date': date,
        'form': form,
    }

    return render(request, 'nurse/create_slot.html', context)

# @method_decorator(login_url=reverse_lazy('login'))
class DateCreate(CreateView):

    model=BookingDate
    fields=['date',]


    def get_initial(self):

         max_date=BookingDate.objects.all().aggregate(Max('date'))
        #  print(max_date)
        #  print(datetime)
         if max_date['date__max'] == None:
              max_date['date__max'] = timezone.now() + datetime.timedelta(days=1)
        #  print(max_date)     
         key, value = max_date.popitem()
        #  value += datetime.timedelta(days=1)
        #  print(value)
        # value=int(list(max_id.values())[0])
        # value=value+1
        # #user = request.user
        #
        #
        # #print(value)
         initial = super(DateCreate, self).get_initial()
         initial.update({'date': value})
         return initial
    def form_valid(self, form):
        user=self.request.user

        profile = Nurse.objects.get(user=user)
        date = form.save(commit=False)
        # print(date)
        try:
            obj = BookingDate.objects.filter(date=str(date)).filter(nurse=profile).first()
        except BookingDate.DoesNotExist:
            obj = None
        # obj=get_object_or_404(BookingDate, date=str(date))
        # print('SHIVAM')
        # print(obj)
        #print(obj.pk)
        if(obj==None):
            # print("no")
            date.nurse = profile
            return super(DateCreate, self).form_valid(form)
        else:
            # print('Yes')
            #return create_slot(self.request,pk=obj.pk-1)
            return redirect(str(obj.pk) + '/slot/')
            #return reverse('doctor_profile:create_slot',kwargs={'pk':int(obj.pk)})
            #return HttpResponse('OK')
            #return super(DateCreate, self).form_invalid(form)
        # context={
        #
		#     "object":appointment,
		# }
		# return render(self.request,'booking/booking_confirmation.html', context=context)


# @login_required(login_url=reverse_lazy('login'))
def show_slots(request):
    user=request.user
    profile = Nurse.objects.get(user=user)
    first_name=profile.first_name
    last_name=profile.last_name
    dates=Slot.objects.filter(nurse=profile).order_by('start_time')
    print(dates)
    return render(request,'nurse/show_slots.html',{'slots':dates,'first_name':first_name,'last_name':last_name})

class ComplaintFeedbackCreate(CreateView):

    model= Nurse_complaint_feedback
    fields=['specify_type','description']


    def form_valid(self, form):
        user=self.request.user

        profile = Nurse.objects.get(user=user)
        feedback = form.save(commit=False)
        feedback.nurse = profile
        feedback.save()
        return redirect('/nurse/home/')
        # print(date)
        # try:
        #     obj = BookingDate.objects.filter(date=str(date)).filter(nurse=profile).first()
        # except BookingDate.DoesNotExist:
        #     obj = None
        # # obj=get_object_or_404(BookingDate, date=str(date))
        # print('SHIVAM')
        # print(obj)
        # #print(obj.pk)
        # if(obj==None):
        #     print("no")
        #     date.nurse = profile
        #     return super(DateCreate, self).form_valid(form)
        # else:
        #     print('Yes')
        #     #return create_slot(self.request,pk=obj.pk-1)
        #     return redirect(str(obj.pk) + '/slots/')
            #return reverse('doctor_profile:create_slot',kwargs={'pk':int(obj.pk)})
            #return HttpResponse('OK')
            #return super(DateCreate, self).form_invalid(form)
        # context={
        #
		#     "object":appointment,
		# }
		# return render(self.request,'booking/booking_confirmation.html', context=context)
def show_complaint_feedback(request):
    user=request.user
    profile = Nurse.objects.get(user=user)
    first_name=profile.first_name
    last_name=profile.last_name
    feedback=Nurse_complaint_feedback.objects.filter(nurse=profile)
    # print(feedback)
    return render(request,'nurse/show_feedback.html',{'feedbacks':feedback,'first_name':first_name,'last_name':last_name})

def delete_slot(request, slot_id):
    # print(request.get['slot_id'])
    Slot.objects.filter(pk=slot_id).delete()
    return redirect('/nurse/slots/')

def show_appointments(request):
    user=request.user
    nurse = Nurse.objects.get(user=user)
    appointments= AppointmentNurse.objects.filter(nurse_id=nurse).filter(status=False).order_by('date').order_by('slot_id')
    first_name=nurse.first_name
    last_name=nurse.last_name
    print(user)
    print(appointments)
    #print(prescriptions[0].pdf)
    #print(prescriptions[0].prescription_date)
    if not appointments:
        context="Hurray No Pending Appointments"
    else:
        context="Pending Appointments"
    # print(appointments[0].date)
    # print(appointments[0].time)
    return render(request,'nurse/nurse_appointments.html',{'context':context,'appointments':appointments,'first_name':first_name,'last_name':last_name})

def work_history(request):
    user=request.user
    physiotherapist = Nurse.objects.get(user=user)
    appointments= AppointmentNurse.objects.filter(nurse_id=physiotherapist).filter(status=True).order_by('date').order_by('slot_id')
    first_name=nurse.first_name
    last_name=nurse.last_name
    print(user)
    print(appointments)
    #print(prescriptions[0].pdf)
    #print(prescriptions[0].prescription_date)
    if not appointments:
        context="Hurray No Pending Appointments"
    else:
        context="Pending Appointments"
    # print(appointments[0].date)
    # print(appointments[0].time)

templates/nurse/bookingdate_form.html
<style>
.card {
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
  max-width: 400px;
  margin: auto;
  /* text-align: center; */
  font-family: arial;
}

.title {
  color: grey;
  font-size: 18px;
}

button {
  border: none;
  outline: 0;
  display: inline-block;
  padding: 8px;
  color: white;
  background-color: #000;
  text-align: center;
  cursor: pointer;
  width: 100%;
  font-size: 18px;
}

a {
  text-decoration: none;
  font-size: 22px;
  color: black;
}

button:hover, a:hover {
  opacity: 0.7;
}
</style>

{% extends 'base.html' %}


{% load static %}
 
<meta name="viewport" content="width=device-width, initial-scale=1">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

  {% block prescription_home %}
 <!-- NAV BAR -->
 <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
  <div class="container">
    <a href='/' class="navbar-brand"><b>HEAL AT HOME</b></a>
    <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a href='{% url "nurse:home" %}'  class="nav-link">Home</a>
  </li>
  <li class="nav-item">
    <a href='{% url "nurse:modify_profile" %}'  class="nav-link">Edit Profile</a>
    </li>
  <li class="nav-item">
    <a href=''  class="nav-link">Bookings</a>
    </li>
  
    <li class="nav-item">
    <a href='/nurse/show_complaint_feedback/'  class="nav-link">Show complaints/feedback</a>
    </li>
  

       
        <li class="nav-item active">
          <a href='' class="nav-link">Logout</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
  <div class="container-fluid" style="background-image:url({% static 'img/dates.jpg' %});background-repeat; background-size:cover;height:650px">
<br><br><br>
    <div class="card">
      <form class="form-horizonatal" action="" method="post">
        {% csrf_token %}<br>
        {% include 'nurse/date-template.html' %}
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-success">Submit </button>
            </div>
            </div>
    </div>
    </div>

{% endblock %}

templates/nurse/complaint-template.html
{% for field in form %}
  <div class="form-group "><br>
    <div class="col-sm-offset-2 col-sm-10">
      <span class="text-danger small">{{field.errors}}</span>
    </div>
    <label class="control-label col-sm-10">{{ field.label_tag}}</label>
    <label class="col-sm-8">{{ field }}</label>
  </div>
{% endfor %}

templates/nurse/create_item_template.html
{% for field in form %}
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <span class="text-danger small">{{field.errors}}</span>
    </div>

    <label class="control-label col-sm-3 text-right">{{ field.label_tag}}</label>
    <label class="col-sm-5 text-left">{{ field }}</label>
  </div>
{% endfor %}

templates/nurse/create_slot.html
{% extends 'base.html' %}


{% load static %}
{% block nurse_slot %}
 <!-- NAV BAR -->
 <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
  <div class="container">
    <a href='/' class="navbar-brand"><b>HEAL AT HOME</b></a>
    <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a href='{% url "nurse:home" %}'  class="nav-link">Home</a>
  </li>
  <li class="nav-item">
    <a href='{% url "nurse:modify_profile" %}'  class="nav-link">Edit Profile</a>
    </li>
  <li class="nav-item">
    <a href=''  class="nav-link">Bookings</a>
    </li>
  
    <li class="nav-item">
    <a href='/nurse/show_complaint_feedback/'  class="nav-link">Show complaints/feedback</a>
    </li>
  

       
        <li class="nav-item active">
          <a href='' class="nav-link">Logout</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
<br><br><br>
<div class='container'>
  <div class="row">
    <div class='col-5' style="background-image:url({% static 'img/appointment.jpg' %});background-repeat; background-size:cover;height:355px">

    </div>
    <div class='col-7'>
      <form class="form-horizontal text-left" action="" method="post" enctype="multipart/form-data">
          <div class="form-group">
            <div class="alert alert-warning">
                <strong>Warning!</strong> Slots once made cannot be modified later
            </div>
            <!-- <div class="alert alert-warning"> -->
            <label style="color:red;">&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp {{message}} </label>
            <!-- </div> -->
        {% csrf_token %}
        {% include 'nurse/create_item_template.html' %}


          <div class="col-sm-offset-2 col-sm-5 text-right">
            <button type="submit" class="btn btn-success">Submit</button>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>

            <br><br><br>
{% endblock %}

templates/nurse/date-template.html
{% for field in form %}
  <div class="form-group ">
    <div class="col-sm-offset-2 col-sm-10">
      <span class="text-danger small">{{field.errors}}</span>
    </div>
    <label class="control-label col-sm-3">{{ field.label_tag}}</label>
    <label class="col-sm-8">{{ field }}</label>
  </div>
{% endfor %}

templates/nurse/new_file.html
<form method="POST" action="">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="save">
</form>

templates/nurse/profile_home.html
<h1> You are currently viewing Profiles app. This is the commom home template </h1>

templates/nurse/profile_template.html
{% for field in form %}
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <span class="text-danger small">{{field.errors}}</span>
    </div>
    <label class="control-label col-sm-3 text-right">{{ field.label_tag}}</label>
    <label class="col-sm-5 text-left">{{ field }}</label>
  </div>
{% endfor %}

templates/nurse/profile_template1.html
{% for field in form %}
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <span class="text-danger small">{{field.errors}}</span>
    </div>
    <label class="control-label col-sm-2">{{ field.label_tag}}</label>
    <div class="col-sm-10">{{ field }}</div>
  </div>
{% endfor %}

templates/nurse/show_appointments.html
{% extends 'base.html' %}

{% load static %}

{% block nurse_show_appointment %}
<!-- NAV BAR -->
<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
  <div class="container">
    <a href='/' class="navbar-brand"><b>HEAL AT HOME</b></a>
    <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a href='{% url "nurse:home" %}'  class="nav-link">Home</a>
  </li>
  <li class="nav-item">
    <a href='{% url "nurse:modify_profile" %}'  class="nav-link">Edit Profile</a>
    </li>
  <li class="nav-item">
    <a href=''  class="nav-link">Bookings</a>
    </li>
  
    <li class="nav-item">
    <a href='/nurse/show_complaint_feedback/'  class="nav-link">Show complaints/feedback</a>
    </li>
  

       
        <li class="nav-item active">
          <a href='' class="nav-link">Logout</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
<div class="container-fluid">

    <div class="col-sm-8 col-md-12" style="padding-right:20px">

        <div class="panel panel-default" style="padding-right:20px">
            <div class="panel-body">
              <br>
              <h3>Dr. {{first_name}}  {{last_name}}  
                <span style="color: blue;font-size: 20px; padding: 1px 45px" >
                  NURSE
                </span>
                </h3> 
                <br><div class="alert alert-warning">
                  These are the Appointments appointed to you along with details of the patient
              </div>

          {% if error_message %}
              <p><strong>{{ error_message }}</strong></p>
          {% endif %}
          <br>
          <table class="table table-striped table-hover ">
              <thead>
              <tr>
                  <th>Date</th>
                  <th>Time</th>
                  <th>Slot Status</th>
                  <!-- <th>RMP Name </th> -->
                  

              </tr>
              </thead>
              <tbody>
              <!-- {% for appointment in appointments %}
                  <tr>
                      <td id="a"> {{appointment.date.date}}</td>
                      <td id="b"> {{appointment.time.start_time}}</td>
                      <td> {{appointment.paitent.first_name}} {{appointment.paitent.last_name}}</td>
                      <td> {{appointment.paitent.symptoms}}</td>
                      <td><a style="pointer-events: none; display: inline-block;" id='attend{{appointment.id}}' href="{{appointment.viedo_chat_link}}"> Attend Patient </a></td>
                      <td><a style="pointer-events: none; display: inline-block;" id='prescription{{appointment.id}}' href='{% url "prescription:Prescription_Add1" appointment_id=appointment.pk %}'> Make Prescription </a></td>
                      <td><button type="button" class="btn btn-default" name="check" onclick='check_link("{{appointment.date}}","{{appointment.time.start_time}}","{{appointment.id}}");'> Refresh </button></td>

                  </tr>
              {% endfor %} -->
              </tbody>
          </table>
          <div class="alert alert-warning">
              {{context}}
          </div>

      </div>
  </div>

</div>

</div>


</br></br></br></br></br></br></br></br></br></br></br></br></br></br>
{% endblock %}

templates/nurse/show_slots.html
{% extends 'base.html' %}


{% load static %}

<!-- <!DOCTYPE html>
<html lang="en">
<head>
  <title>Prescription</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
   -->
  {% block nurse_show_slots %}

     <!-- NAV BAR -->
     <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
      <div class="container">
        <a href='/' class="navbar-brand"><b>HEAL AT HOME</b></a>
        <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a href='{% url "nurse:home" %}'  class="nav-link">Home</a>
			</li>
			<li class="nav-item">
				<a href='{% url "nurse:modify_profile" %}'  class="nav-link">Edit Profile</a>
			  </li>
			<li class="nav-item">
				<a href=''  class="nav-link">Bookings</a>
			  </li>
			
			  <li class="nav-item">
				<a href='/nurse/show_complaint_feedback/'  class="nav-link">Show complaints/feedback</a>
			  </li>
			

           
            <li class="nav-item active">
              <a href='' class="nav-link">Logout</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  <div class="container-fluid">
          <div class="col-sm-8 col-md-9">

              <div class="panel panel-default">
                  <div class="panel-body">
                    <br>
                    <h3>Dr. {{first_name}}  {{last_name}}  
                      <span style="color: blue;font-size: 20px; padding: 1px 45px" >
                        NURSE
                      </span>
                      </h3> 
                     
                      <br>
                      {% if error_message %}
                          <p><strong>{{ error_message }}</strong></p>
                      {% endif %}
                      <div class="alert alert-warning">
                        Only Available Slots can be deleted to cancel booked slots contact admin
                    </div>

                      <table class="table table-striped table-hover ">
                          <thead>
                          <tr>
                              <th>Date</th>
                              <th>Time</th>
                              <th>Slot Status</th>
                              <!-- <th>RMP Name </th> -->

                          </tr>
                          </thead>
                          <tbody>
                          {% for slot in slots %}
                              <tr>
                                  <td> {{slot.date.date}}</td>
                                  <td> {{slot.start_time}}</td>
                                  <td> {% if slot.slot_status %} Booked {% else %} Available {% endif %}       </td>
                                  {% if slot.slot_status %}
                                  <td> </td>
                                  {% else %}    
                                       <td><a style="pointer-events: auto; display: inline-block;"  href='{% url "nurse:delete_slot" slot_id=slot.pk %}'> Delete Slot </a></td>
                                  {% endif %}
                                </tr>
                          {% endfor %}
                          </tbody>
                      </table>

                  </div>
              </div>

          </div>

      </div>


      </br></br></br></br></br></br></br></br></br></br></br></br></br></br>
      {% endblock %}

</body>
</html>